### ISSUE TITLE
Dynamic image resizing

### ISSUE THREAD

**Issue by parrish** [zooniverse/static#13]
How would you feel about a freeform image resize for thumbnails?

Something like:
```
if ($uri ~ ^/([0-9]+)x([0-9]+)/) {
  set $width $1;
  set $height $2;
}
```

Or if you wanted to limit the image dimensions to say 1-999 px:

```
if ($uri ~ ^/([1-9][0-9]{0,2})x([1-9][0-9]{0,2})/) {
  set $width $1;
  set $height $2;
}
```

**Comment by astopy** [comment]
Ah, I like it! I’d thought of doing something like the first example but was concerned that there’d be no upper limit to the image size, but I hadn’t thought of just limiting the number of digits in the regex.

I’ll put that in now.

**Comment by parrish** [comment]
Cool, thanks!
