### ISSUE TITLE
non-ascii s3 paths are not accessible via static proxy

### ISSUE THREAD

**Issue by camallen** [zooniverse/static#144]
We're seeing some issues with the nginx static proxy when requesting encoded URLs, e.g. requesting
- https://talk.sunspotter.org/users/王可萱/index.html

the browser will send this encoded URL request
- https://talk.sunspotter.org/users/%E7%8E%8B%E5%8F%AF%E8%90%B1/index.html

The above request responds with `404 Not Found`

However accessing the encoded URL directly via s3 returns the document
- https://zooniverse-static.s3.amazonaws.com/talk.sunspotter.org/users/%E7%8E%8B%E5%8F%AF%E8%90%B1/index.html

For ascii based URLs we don't experience this issue, e.g. the following urls both resolve to the s3 objects
- https://zooniverse-static.s3.amazonaws.com/talk.sunspotter.org/users/yshish/index.html
- https://talk.sunspotter.org/users/yshish/index.html

Looking into how our s3 proxy is setup, https://github.com/zooniverse/static/blob/1572db64aaeb38d904e1a60de00e9f06871414df/nginx-proxy.conf#L7

I believe this is due to our use of `$uri` var in the above proxy pass, my reading suggests using `$uri` will decode the request URI before being passed to the proxy, http://nginx.org/en/docs/http/ngx_http_core_module.html#var_uri. 

Based on the nginx docs, it appears we should be using `$request_uri` to avoid any decoding and allow the requesting client (browser) to encode these URLs for us. https://stackoverflow.com/questions/48708361/nginx-request-uri-vs-uri/48709976

I'd be happy to make this change, perhaps on a different test location/server block. Thoughts?

**Comment by adammcmaster** [comment]
This sounds fine to me. You can test it locally in Docker easily enough using curl.

From the docs it sounds like `$request_uri` includes the query string, so I guess the S3 URL would become `http://zooniverse-static.s3-website-us-east-1.amazonaws.com/$host$request_uri`
