### ISSUE TITLE
Optimize ingress application

### ISSUE THREAD

**Issue by zwolf** [zooniverse/static#237]
During deploys of this app, a large number of k8s yaml templates are applied in extremely rapid succession. Take it away, @camallen:

This causes a large amount of IO on the k8s nodes that run our traffic ingress in K8s land (2 pods by default so most likely on 2 distinct nodes). Those IO operations cause a backlog in kernel OS operations on those nodes and they stop responding properly (read incoming traffic stops working)

I tried a remedial step to slow the application of these ingress declarations to space them out over time but it didn’t help much, https://github.com/zooniverse/static/pull/231. 

a better longer term solution would be to 
* extract these ingress declarations to their own deployment area, isolated from the nginx static proxy changes (like your project redirect) 
* move each ingress directive to the repository that ‘owns’ the ingress
* for repos that aren’t actively maintained / deployed (these should be few) we leave them ‘lumped’ together in the outcome from point 1
* add different ingress controllers (production / staging / the rest) for different traffic patterns and assign deployments to each one

The changes above should mean we have smaller ingress change sets on deploys that don’t cause so much IO on the nodes and/or partition the traffic across more nodes to avoid single points of failure.

**Comment by camallen** [comment]
I've made a start on service ingress extraction in https://github.com/zooniverse/hamlet/pull/411 and https://github.com/zooniverse/static/pull/260

Also that extracted hamlet ingress has the new ingress annotations for k8s v1.22 and higher https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by zwolf** [comment]
Fixed by https://github.com/zooniverse/static/pull/277 and many others.
