### ISSUE TITLE
Set up routing for NextJS static assets

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/static#251]
I'm not sure if this is the best place to ask this, but can we set up the following routing for NextJS app data so that browsers request it via our CDN.

- `www.zooniverse.org/projects/_next` => `fe-project.zooniverse.org/projects/_next`
- `www.zooniverse.org/about/_next` => `fe-project.zooniverse.org/about/_next`
- `frontend.preview.zooniverse.org/projects/_next` => `fe-project.preview.zooniverse.org/projects/_next`
- `frontend.preview.zooniverse.org/about/_next` => `fe-project.preview.zooniverse.org/about/_next`

Related monorepo PR, which sets up asset prefixes in NextJS: https://github.com/zooniverse/front-end-monorepo/pull/2519

Related monorepo issue: https://github.com/zooniverse/front-end-monorepo/issues/2518

**Comment by camallen** [comment]
Yes - i think we should do this to allow custom CDN behaviours for our FEM apps without touching the CDN configs. This helps as it'll provide

1. visibility into the CDN rules - no need to have FD Azure portal access
2. Allow change PRs from all devs not folks with Front Door azure access
3. Decrease FD costs
4. Standardize the CDN traffic patterns - client -> FD -> Static Nginx proxy -> FEM / Blob services

**Comment by eatyourgreens** [comment]
I've added a couple of rules to FrontDoor, so that PH-TESS isn't broken on the live site.
eg. https://www.zooniverse.org/projects/_next/data/f76IJxhkZ_A8LzoWQAaqM/nora-dot-eisner/planet-hunters-tess.json?owner=nora-dot-eisner&project=planet-hunters-tess

Totally agree about managing these via PR rather than FrontDoor settings, mostly for better visibility and change management.

**Comment by eatyourgreens** [comment]
Also noting here that NextJS totally ignores the configured asset prefix for those data requests. Probably a same-origin or CORS thing.
https://github.com/zooniverse/front-end-monorepo/blob/21b073aff0e8aae6c569ed8cb6ab1e6df6ac49a0/kubernetes/deployment-production.tmpl#L70-L72
