### ISSUE TITLE
Redirect Andromeda Project to PBBP

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/static#85]
**Current Behavior**: andromedaproject.org points to the Ouroboros-built version of the project.

**Desired Behavior**: andromedaproject.org points to the PBBP [https://www.zooniverse.org/projects/zooniverse/andromeda-project](https://www.zooniverse.org/projects/zooniverse/andromeda-project).

Also, the URL [http://www.andromedaproject.org/#!/authors](http://www.andromedaproject.org/#!/authors) is published in a journal article.  Please ensure that following this link leads to the PFE project page (acceptable) or the [team page](https://www.zooniverse.org/projects/zooniverse/andromeda-project/about/team) where the authors are listed at the bottom (best case, but not essential), but not a dead link / page not found (unacceptable).

Once redirect is complete, Ouroboros version of the project can be shut down.

**Comment by eatyourgreens** [comment]
Hi Cliff, the `#!/authors` part of the URL is handled by your web browser, not by our servers. Essentially that URL says to the browser 'fetch https://www.andromedaproject.org then jump to the `!/authors` section of the returned page.' Which all essentially means it can't be redirected by us here but rather that PFE would have to be updated (if possible) to handle that URL.

**Comment by camallen** [comment]
I think we'll have to handle it like we've done for other pages, i.e. via deployed JS on that domain that redirects. Example code here https://github.com/zooniverse/retirement/blob/953ad898381f23e8bf633d088b9757d4c3a8519f/BatDetective/js/main.js#L2

**Comment by eatyourgreens** [comment]
@camallen https://www.andromedaproject.org is supposed to redirect to a PFE project now.

**Comment by camallen** [comment]
Yep, we can't deal with that via nginx redirects sadly. I don't think we should be adding functionatlity to PFE to handle this either. 

Instead it can be done like Bat Detective, with a deployed retirement page that interprets the URL client side and redirects via JS. Default redirect will be to new project root, authors page should redirect to the PFE project team page instead.

Is there a better solution than a HTML / JS redirection page?

**Comment by eatyourgreens** [comment]
I'm not sure. At the moment, that URL loads the project home page (as expected.) https://www.zooniverse.org/projects/zooniverse/andromeda-project/#!/authors

**Comment by eatyourgreens** [comment]
There's some code to redirect fragment identifiers that begin with `/`. That could be changed to  include IDs that begin with `!/`, I guess. https://github.com/zooniverse/Panoptes-Front-End/blob/33eb94aaa1a3b1827287c4aadb9c516c74b1d877/app/main.cjsx#L18-L28

Actually, re-reading the original description here then loading the project page is acceptable.

**Comment by camallen** [comment]
> Please ensure that following this link leads to the PFE project page (acceptable) or the team page where the authors are listed at the bottom (best case, but not essential), but not a dead link / page not found (unacceptable).

> At the moment, that URL loads the project home page (as expected.) 

That sounds good. I'm wondering about the new rebuild switch, I can't see a reason why the rebuild would not offer the same functionality of rendering the landing page as it's a fragment after a valid project URL, right? 

@lcjohnso - can you confirm that if as you say then falling back to just the landing page in PFE project is acceptable then we can deal with this without deploying custom HTML / JS to handle the redirect. It'll just mean the existing links won't land you directly on any team / authors page, users will have to navigate to find that content. 

Let us know if this is ok and if not, there are ways to deal with the redirect to a valid team/authors page.

**Comment by eatyourgreens** [comment]
>That sounds good. I'm wondering about the new rebuild switch, I can't see a reason why the rebuild would not offer the same functionality of rendering the landing page as it's a fragment after a valid project URL, right?

The request that's sent to the server is `GET https://www.andromedaproject.org/`, which retrieves the project home page regardless. It's then up to the browser how it handles the hash fragment. The new app could have client-side JS to handle fragments, but it seems clunky.

**Comment by lcjohnso** [comment]
Hi @eatyourgreens + @camallen: Yes, I confirm that having the URL with `#!/authors` redirect to the PFE project home page is OK.  I thought I would ask about the possibility of a redirect to the `/about/team` page if there was an easy option that came to mind, but totally agree that this isn't worth spending dev time to enable.  The traffic to that URL is *tiny* but non-zero, so as long as it doesn't redirect to 404, then we're good.

Thanks for taking the time to think through the options!

**Comment by camallen** [comment]
@lcjohnso i've got a fix up in #87 - is it ok to merge and redirect all traffic to PFE?

**Comment by lcjohnso** [comment]
@camallen Make it so!
